### ISSUE TITLE
Translatable Text

### ISSUE THREAD

**Issue by ItsJuls** [NeumimTo/TownyColonies#2]
having translatable text should be good for people to have the messages be done in crowdin and stuff like this
![image](https://github.com/NeumimTo/TownyCivs/assets/79675118/3aa4948c-32e4-44a8-ab58-63ad84128681)
![image](https://github.com/NeumimTo/TownyCivs/assets/79675118/6549774f-ac7d-4bfd-867d-8afe2c9fd101)

**Comment by NeumimTo** [comment]
you can edit some of the messages here 

https://github.com/NeumimTo/TownyCivs/tree/master/src/main/resources/lang
https://github.com/NeumimTo/TownyCivs/tree/master/src/main/resources/gui

im not planning to create crowdin atm as at this point most of messages are subject to change.
